# Generated by Django 5.2.10 on 2026-02-28 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_event_rejection_reason_alter_attendeeprofile_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendee_withdrawal_policy",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="withdrawal_policy",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="preparation_status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AddField(
            model_name="request",
            name="update_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("organizer", "Organizer"), ("vendor", "Vendor")],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.event",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.vendorprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VendorStatusUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=50)),
                ("note", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("vendor", "Vendor"), ("system", "System")],
                        max_length=20,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="core.request",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EventMessage",
        ),
    ]
