# Generated by Django 5.2.10 on 2026-04-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_event_attendee_withdrawal_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
