# Generated by Django 5.2.10 on 2026-04-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeprofile",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
