# Generated by Django 5.2.10 on 2026-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_attendeeprofile_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="event_banners/"),
        ),
    ]
